package com.scriptmd.service;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.draw.LineSeparator;
import com.scriptmd.model.Prescription;
import com.scriptmd.repository.PrescriptionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class PrescriptionService {

    @Autowired
    private PrescriptionRepository repository;

    // Save prescription to database
    public Prescription save(Prescription prescription) {
        return repository.save(prescription);
    }

    // Get all prescriptions newest first
    public List<Prescription> getAll() {
        return repository.findAllByOrderByCreatedAtDesc();
    }

    // Get one prescription by its ID
    public Prescription getById(Long id) {
        return repository.findById(id).orElse(null);
    }

    // Get all prescriptions for one patient using ID
    public List<Prescription> getByPatientId(Long patientId) {
        return repository.findByPatientId(patientId);
    }

    // Search prescriptions by patient name
    public List<Prescription> searchByPatientName(String name) {
        return repository.findByPatientNameContaining(name);
    }

    // Generate PDF for a prescription
    public byte[] generatePdf(Prescription p) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, out);
        document.open();

        Font titleFont  = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);
        Font headerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
        Font normalFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL);
        Font smallFont  = new Font(Font.FontFamily.HELVETICA, 9,  Font.ITALIC);

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("MMMM dd, yyyy HH:mm");

        Paragraph title = new Paragraph("ScriptMD Medical Prescription", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph("Generated: " + p.getCreatedAt().format(fmt), smallFont));
        document.add(Chunk.NEWLINE);
        document.add(new Chunk(new LineSeparator()));
        document.add(Chunk.NEWLINE);

        document.add(new Paragraph("Patient: " + p.getPatientName(), headerFont));
        document.add(new Paragraph("Patient ID: " + p.getPatientId(), headerFont));
        document.add(new Paragraph("Doctor: "  + p.getDoctorName(),  headerFont));
        document.add(Chunk.NEWLINE);

        document.add(new Paragraph("Symptoms", headerFont));
        document.add(new Paragraph(p.getSymptoms() != null ? p.getSymptoms() : "Not specified", normalFont));
        document.add(Chunk.NEWLINE);

        document.add(new Paragraph("Medicine Prescribed", headerFont));
        document.add(new Paragraph(p.getMedicine(), normalFont));
        document.add(Chunk.NEWLINE);

        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        BaseColor lightBlue = new BaseColor(173, 216, 230);

        addCell(table, "Dosage",    headerFont, lightBlue);
        addCell(table, "Frequency", headerFont, lightBlue);
        addCell(table, "Duration",  headerFont, lightBlue);
        addCell(table, p.getDosage()    != null ? p.getDosage()    : "-", normalFont, BaseColor.WHITE);
        addCell(table, p.getFrequency() != null ? p.getFrequency() : "-", normalFont, BaseColor.WHITE);
        addCell(table, p.getDuration()  != null ? p.getDuration()  : "-", normalFont, BaseColor.WHITE);
        document.add(table);
        document.add(Chunk.NEWLINE);

        document.add(new Chunk(new LineSeparator()));
        document.add(new Paragraph("Generated by ScriptMD AI System | Prescription ID: #" + p.getId(), smallFont));

        document.close();
        return out.toByteArray();
    }

    private void addCell(PdfPTable table, String text, Font font, BaseColor bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(8);
        table.addCell(cell);
    }
}